sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: dbconn.sealoshzh.site
    port: 
    database: sky_take_out
    username: root
    password: 
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: java-cqwm-dois
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
spring:
  redis:
    host: dbconn.sealoshzh.site
    port: 
    password: 

